**** Platform Direct3D 11:
Compiled code for kernel CSMain:
binary blob size 480:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
      cs_5_0
      dcl_globalFlags refactoringAllowed
      dcl_resource_structured t0, 4
      dcl_resource_structured t1, 4
      dcl_uav_structured u0, 36
      dcl_input vThreadID.x
      dcl_temps 1
      dcl_thread_group 10, 1, 1
   0: mov r0.x, vThreadID.x
   1: mov r0.yzw, l(0,0,0,0)
   2: store_structured u0.xyzw, vThreadID.x, l(0), r0.xyzw
   3: ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(0), t0.xxxx
   4: mov r0.xyz, l(0,0,0,0)
   5: store_structured u0.xyzw, vThreadID.x, l(16), r0.xyzw
   6: ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, vThreadID.x, l(0), t1.xxxx
   7: ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.x, l(0), t0.xxxx
   8: store_structured u0.x, vThreadID.x, l(32), r0.x
   9: ret 
// Approximately 0 instruction slots used




